/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChavesPublicasRouteImport } from './routes/chaves-publicas'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as LeiDaMeiaEntradaRouteImport } from './routes/lei-da-meia-entrada'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChavesPublicasRoute = ChavesPublicasRouteImport.update({
  id: '/chaves-publicas',
  path: '/chaves-publicas',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const LeiDaMeiaEntradaRoute = LeiDaMeiaEntradaRouteImport.update({
  id: '/lei-da-meia-entrada',
  path: '/lei-da-meia-entrada',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chaves-publicas': typeof ChavesPublicasRoute
  '/faq': typeof FaqRoute
  '/lei-da-meia-entrada': typeof LeiDaMeiaEntradaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chaves-publicas': typeof ChavesPublicasRoute
  '/faq': typeof FaqRoute
  '/lei-da-meia-entrada': typeof LeiDaMeiaEntradaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chaves-publicas': typeof ChavesPublicasRoute
  '/faq': typeof FaqRoute
  '/lei-da-meia-entrada': typeof LeiDaMeiaEntradaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chaves-publicas' | '/faq' | '/lei-da-meia-entrada'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chaves-publicas' | '/faq' | '/lei-da-meia-entrada'
  id: '__root__' | '/' | '/chaves-publicas' | '/faq' | '/lei-da-meia-entrada'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChavesPublicasRoute: typeof ChavesPublicasRoute
  FaqRoute: typeof FaqRoute
  LeiDaMeiaEntradaRoute: typeof LeiDaMeiaEntradaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chaves-publicas': {
      id: '/chaves-publicas'
      path: '/chaves-publicas'
      fullPath: '/chaves-publicas'
      preLoaderRoute: typeof ChavesPublicasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lei-da-meia-entrada': {
      id: '/lei-da-meia-entrada'
      path: '/lei-da-meia-entrada'
      fullPath: '/lei-da-meia-entrada'
      preLoaderRoute: typeof LeiDaMeiaEntradaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChavesPublicasRoute: ChavesPublicasRoute,
  FaqRoute: FaqRoute,
  LeiDaMeiaEntradaRoute: LeiDaMeiaEntradaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
